# Site settings
title: MyPaint
description: "MyPaint is an easy-to-use painting program which works well with Wacom graphics tablets and other similar devices. It comes with a large brush collection including charcoal and ink to emulate real media, but the highly configurable brush engine allows you to experiment with your own brushes and with not-quite-natural painting."
baseurl: ""
url: "http://mypaint.org"
twitter_username: MyPaintApp
github_username:  mypaint

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "on"

theme: jekyll-theme-minimal